### ISSUE TITLE
Consider switching to using git submodules instead of manually checking out repos

### ISSUE THREAD

**Issue by dylanede** [google/shaderc-rs#10]
This would make managing the dependencies on other repositories much more straightforward and less error prone. For example, at the moment a clean build will work, but if you try to build again after that it will fail, since the `git pull` commands fail due to the checked out repos not being on a branch (instead they are pinned to a commit). With git submodules you can remove all of the git related code from the build script.

**Comment by dylanede** [comment]
In the short term, fixing the current problem with `git pull` can be done by using `git fetch` instead.

**Comment by antiagainst** [comment]
Thanks for the suggestion! It's done in #13.

shaderc requires a certain directory hierarchy for its dependencies. Right now shaderc itself does not manage its dependencies as Git submodules. To use Git submodule here, we need to register nested submodules (in shaderc-rs), which I don't think Git supports right now. So I created an umbrella `CMakeLists.txt` to include all projects.
