### ISSUE TITLE
Updating shaderc version

### ISSUE THREAD

**Issue by hodasemi** [google/shaderc-rs#100]
Hi, 

can we get an updated shaderc version for GL_EXT_ray_tracing? Compiling following shader results in an error when I try to create a shader module.

```
#version 460
#extension GL_EXT_ray_tracing : enable

void main() {}
```

```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x5555581a6dc8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Operand 1 of EntryPoint requires one of these capabilities: RayTracingKHR RayTracingNV 
  OpEntryPoint RayGenerationNV %main "main"
```

**Comment by antiagainst** [comment]
Hi, I created #100 to update the native projects. Note that this will only be useful if you build from source. If you use shaderc libraries from, say, Vulkan SDK, you'll need to update there. :)

**Comment by hodasemi** [comment]
Thanks, it works for me. Is it possible to update crate version to 0.7.1 to update the changes to crates.io?

**Comment by antiagainst** [comment]
v0.7.1 published now. Closing this.
