### ISSUE TITLE
Can Compiler be Send, even Sync?

### ISSUE THREAD

**Issue by chubei-oppen** [google/shaderc-rs#113]
The comments [here](https://github.com/google/shaderc/blob/f6d6dddfabfec1041c0dfb8e7ff3608a5f82227c/libshaderc/include/shaderc/shaderc.h#L245) seems to imply `Compiler` can be both `Send` and `Sync`.

**Comment by kocsis1david** [comment]
It's strange that the compiler definition (`typedef struct shaderc_compiler* shaderc_compiler_t;`) is a non-const pointer.
