### ISSUE TITLE
Crates that use shaderc at build time fail to build on docs.rs

### ISSUE THREAD

**Issue by marc0246** [google/shaderc-rs#144]
#130 made shaderc unable to build on docs.rs at all. That's fine for building the crate itself, and crates depending on it, however some crates use shaderc *at build time*. See rust-lang/docs.rs#2329 for the issues this causes and the affected crates.

**Comment by antiagainst** [comment]
Oops sorry about it! I don't know what's the best way to handle this; maybe add another environment variable like `SHADERC_DOC_BUILD_FORCE_LINK` and use that in vulkano-shaders or a feature similar to that?

**Comment by marc0246** [comment]
It's an understandable oversight.

I hope no one takes this the wrong way, as I don't mean to offend, but to me #130 seems like either a solution to a problem that didn't exist in the first place or the wrong solution. So my solution would be to revert #130 and solve whatever issue @chyyran was actually having. Maybe I'm missing something, and some change before #130 broke cross-compilation on docs.rs or something, however if you look at the reverse dependencies of shaderc you will see that the crates have been building just fine (including cross-compilation) before. Usually the first place to look when there's a docs.rs build failure is the package metadata, so maybe removing the `package.metadata.docs.rs.targets` field from @chyyran's crate will help. Or maybe @chyyran has some insight as to why their crate fails to build unlike all the others.

In any case, I maintain that penalizing all the other crates is insanity. Worst case scenario would be to simply not cross-compile on docs.rs.

**Comment by marc0246** [comment]
After further inspection it appears that cross-compilation hasn't worked for any crate, exept ones that use shaderc only at build time or as an optional dependency, so I was wrong on that. Makes sense. I wish I knew how to solve this without resorting to unclean solutions. Would it even be possible to cross-compile shaderc?

**Comment by chyyran** [comment]
fwiw, #130 fixes docs.rs builds for `x86_64-pc-windows-msvc`. Versions prior simply could not build docs for this target and others at all if it depended on shaderc, this is clear if you look at docs for shaderc [before 0.8.2](https://docs.rs/shaderc/0.8.1/shaderc/index.html). This is understandably an issue for _libraries_ that are Windows-focused: providing only Linux docs means my users won't be able to see docs regarding Direct3D integration.

**Comment by marc0246** [comment]
Makes sense, I made a patchwork PR trying to make it work in build scripts and proc-macros.
