### ISSUE TITLE
Error when trying to launch program.

### ISSUE THREAD

**Issue by thelearnerofcode** [google/shaderc-rs#20]
Hello, when I try to load my program straight from the targets/release directory, I get this errror:
`./test_assets: error while loading shared libraries: libshaderc_shared.so: cannot open shared object file: No such file or directory`.

However, it works fine when I run it with `cargo run --release`

**Comment by antiagainst** [comment]
Urgh. You are right. For historical reasons, Linux and MacOS are still trying to use the shared library right now:

https://github.com/google/shaderc-rs/blob/52bd9f9aa70bcaf99fbb7524cec490448cd680f7/build/build.rs#L68-L72

When calling your binary directly, the path to the compiled shared binary is missing, which causes the crash. I should convert them to use the static library to be safe. Will fix. Thanks for reporting!

**Comment by antiagainst** [comment]
#21 to address this issue.

**Comment by antiagainst** [comment]
Fixed via #21.
