### ISSUE TITLE
CompileOptions::set_generate_debug_info() does not emit OpLine and opSource including the original code

### ISSUE THREAD

**Issue by nicokoch** [google/shaderc-rs#22]
GLSLang gained the ability to do this with https://github.com/KhronosGroup/glslang/commit/44d2728e3d45bd064a4e6bf23d9c1793dc0da839

I need these debug instructions for a spirv debugger I'm currently creating.
It would be nice if shaderc-rs generated these OpCodes... not sure if shaderc itself supports this already, but the foundation has been laid in GLSLang (pass -g)

**Comment by antiagainst** [comment]
I don't think Shaderc supports this right now. I'll look into it and add the functionality to Shaderc first.

**Comment by antiagainst** [comment]
Filed https://github.com/google/shaderc/issues/455 for Shaderc support of this.

**Comment by nicokoch** [comment]
Thanks :)

**Comment by antiagainst** [comment]
https://github.com/google/shaderc/issues/455 was implemented and closed long time ago. Marking as fixed and closing this one too.
