### ISSUE TITLE
Compiling with --no-default-features

### ISSUE THREAD

**Issue by ennis** [google/shaderc-rs#36]
I ran into issue #33 and as a workaround, I wanted to provide my own version of the shaderc_combined library instead of compiling in build.rs. The readme suggests this is possible by disabling default features and putting the library in the correct target/deps directory, but this does not seem to work: the linker does not find the shaderc_* symbols (also the native library doesn't seem to be passed into the linker arguments).

I might be forgetting something obvious that's needed for linking with the native library, but the readme doesn't say a lot on this particular use case.

**Comment by antiagainst** [comment]
Hey @ennis, sorry about that. It seems building with `--no-default-features` has gone stale for a while. I committed https://github.com/google/shaderc-rs/commit/2069b5aceafa61421deccaea9714cce960bd36da to improve it. Will prepare a release soon.

**Comment by antiagainst** [comment]
Pushed out v0.3.14 including the fix. Let me know if it still has problems. Thanks!

**Comment by ennis** [comment]
I can see the new warning, and putting the lib at the specified location works perfectly. Thanks!
