### ISSUE TITLE
Adding iOS runtime

### ISSUE THREAD

**Issue by seivan** [google/shaderc-rs#40]
Is there any chance of adding an iOS runtime by adding support for other targets in `build.rs`?

**Comment by antiagainst** [comment]
Hey @seivan, that sounds good to me! But I'm not familiar with iOS and its development. So contributions welcomed! :)

**Comment by seivan** [comment]
So the initial question would be, can shaderc (and all its dependency) run on arm?

**Comment by antiagainst** [comment]
Well, Shaderc can be used for runtime compilation on Android: https://developer.android.com/ndk/guides/graphics/shader-compilers#runtime

**Comment by seivan** [comment]
@antiagainst So the issue here is to get the Shaderc project to build for arm/iOS - is that something that's related to this crate? 

Edit so Shaderc and all its dependencies would have to build for arm. My initial issue was not having access to `glslang` at runtime.

**Comment by antiagainst** [comment]
AFAICT, Shaderc right now does not support compilation on iOS, or no one has tried it. To make it (the C++ project) compile on iOS is not something that should go into this crate. But this crate itself (the Rust wrapper) also lacks iOS support.

**Comment by bschwind** [comment]
@seivan I know this is an older issue, but I believe I was able to compile and use this crate for ios via Rendy and gfx-hal.

See the PR for example code here:

https://github.com/amethyst/rendy/pull/218/files

There were some issues building this crate so see the README I included there.

**Comment by seivan** [comment]
@bschwind I've already managed to get it to work but I had to change a lot of the upstream dependencies (like `glslang`)  - did you manage to make it work without doing so?

**Comment by bschwind** [comment]
I had to modify a `CMakeCache.txt` file to change the `CMAKE_OSX_SYSROOT` environment variable to point to an iOS SDK instead of the MacOS one.

I didn't need to make any other changes. It built and ran on iOS so I'm assuming it all went well.

**Comment by simlay** [comment]
This looks like it will fix this issue https://github.com/alexcrichton/cmake-rs/pull/88

**Comment by antiagainst** [comment]
Closing given #83 is landed.
