### ISSUE TITLE
Ray Tracing Shader Support

### ISSUE THREAD

**Issue by hodasemi** [google/shaderc-rs#52]
Hey,

the title does actually say all ...

Add support to build various ray tracing shader (.rgen, .rint, .rahit, .rchit, .rmiss, .rcall). I can already convert these shader types from glsl to spir-v on command line, it would be nice to have it automated.

**Comment by hodasemi** [comment]
I have done some testing and created a pull request: https://github.com/google/shaderc-rs/pull/53
You may want take a look.

Some bot tells me to agree something, wtf ... ?!

**Comment by antiagainst** [comment]
I think this should be completed with #53?

**Comment by hodasemi** [comment]
Yes, exactly. Thanks for merging!
