### ISSUE TITLE
Wrapping shaderc_compile_options_set_include_callbacks

### ISSUE THREAD

**Issue by dylanede** [google/shaderc-rs#6]
I'd be interested in having support for this in shaderc-rs so that sources can use include directives. I think I'll write a PR for this but I've opened this issue in case anyone else wants to discuss this.

**Comment by antiagainst** [comment]
Sounds good to me! I'm not working on it. Thanks for contributing @dylanede!

**Comment by dylanede** [comment]
Fixed in #11.
