### ISSUE TITLE
Tests no longer pass

### ISSUE THREAD

**Issue by dylanede** [google/shaderc-rs#7]
Since the build script doesn't pin the pulled repos to a particular commit, it picks the latest versions of each of them. As well as potentially silently introducing breakage or errors, this has caused the tests to fail. Presumably the best way of dealing with this is to checkout particular commits in the build script, instead of blindly updating.

**Comment by antiagainst** [comment]
Fair point.

Actually shaderc itself provides a [`known_good`](https://github.com/google/shaderc/tree/known-good) branch that we can leverage maybe. But right now it's quite out of date. So for this time, I may want to use top of the tree for all projects.

**Comment by antiagainst** [comment]
https://github.com/google/shaderc-rs/commit/6018e40bd8db939e6d911ff3c683714194c256f3 For this.
