### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by repi** [google/shaderc-rs#72]
Been 7 months since the last release to crates.io, possible to publish a new one? 

Specifically after getting a release with the merged PR #68 that we did.

Thanks!

**Comment by antiagainst** [comment]
Sure, will do. Thanks for the reminder!

**Comment by antiagainst** [comment]
Done with https://github.com/google/shaderc-rs/commit/c455e8046afbb2da3351eb17fa06c38bc6686d59.
