### ISSUE TITLE
Try to use rust-bindgen to generate FFI bindings

### ISSUE THREAD

**Issue by antiagainst** [google/shaderc-rs#8]

**Comment by dylanede** [comment]
One disadvantage to this approach at the moment is that getting bindgen to work correctly with clang msvc compatibility at the moment is not straightforward (it's doable, but far from user-friendly - see https://github.com/rust-lang-nursery/rust-bindgen/issues/975), and requires extra environment configuration from the user. Bindgen also requires a libclang installation to build.

**Comment by antiagainst** [comment]
Thanks for the warnings, @dylanede! Apparently I'm just attracted by this shiny new thing (well, to me). Based on what you've said, maybe I should just delay trying this.

**Comment by antiagainst** [comment]
Closing since I won't work on this.
