### ISSUE TITLE
Update shaderc-rs (and shaderc-sys) on crates.io please

### ISSUE THREAD

**Issue by simlay** [google/shaderc-rs#84]
The folks over at https://github.com/bevyengine/bevy/pull/539#issuecomment-703835175 want the addition of #83 on crates.io, to have iOS support in bevy in an upcoming release. Could someone push a new version to cratesi.o please?

Thanks!

**Comment by antiagainst** [comment]
Sure thing. Thanks for the ping. Will do shortly.

**Comment by antiagainst** [comment]
Looks like #83 has some issues with Travis CI. I'll fix it first and then publish a new release.

**Comment by antiagainst** [comment]
A new release is published. Sorry about the long wait!
