### ISSUE TITLE
Extensions?

### ISSUE THREAD

**Issue by charles-r-earp** [google/shaderc-rs#98]
It would be nice to have way to add `#extension` directives in a similar way to how macros are added. For whatever reason, glsl requires extensions to be first so macros cannot be used to specify extensions. This looks like something that would have to be added to shaderc.

**Comment by antiagainst** [comment]
Yeah. shaderc-rs is just a wrapper around the native shaderc library. So the functionality should be available there first. Please feel free to request there. :)
